version: '3.4'
services:
         kstream:
                build: ./Kstream
                container_name: kstream
                network_mode: "host"
         klinker:
                build: ./Klinker
                container_name: klinker
                network_mode: "host"    
         relklinker:
                build: ./Relklinker
                container_name: relklinker
                network_mode: "host"
         katz:
                build: ./Katz
                container_name: katz
                network_mode: "host"
         pathent:
                build: ./Pathent
                container_name: pathent
                network_mode: "host"
         simrank:
                build: ./Simrank
                container_name: simrank
                network_mode: "host"
