version: '3.4'
services:
         kstream:
                build: ./Kstream
                container_name: kstream
                network_mode: "host"
         klinker:
                build: ./Klinker
                container_name: klinker
                network_mode: "host"    
         relklinker:
                build: ./Relklinker
                container_name: relklinker
                network_mode: "host"
         katz:
                build: ./Katz
                container_name: katz
                network_mode: "host"
         pathent:
                build: ./Pathent
                container_name: pathent
                network_mode: "host"
         simrank:
                build: ./Simrank
                container_name: simrank
                network_mode: "host"
         adamic_adar:
                build: ./AdamicAdar
                container_name: adamic_adar
                network_mode: "host"
         degree_product:
                build: ./DegreeProduct
                container_name: degree_product
                network_mode: "host"
         jaccard:
                build: ./Jaccard
                container_name: jaccard
                network_mode: "host"
         pra:
                build: ./Pra
                container_name: pra
                network_mode: "host"
         predpath:
                build: ./Predpath
                container_name: predpath
                network_mode: "host"
